image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
   - ps: $App = Start-Process -FilePath java -ArgumentList "-jar ./artifacts/app-card-delivery.jar" -PassThru


build_script:
  - chmod +x gradlew
  - ./gradlew test -Dselenide.headless=true
  - ./gradlew test --info
